### ISSUE TITLE
v2 content

### ISSUE THREAD

**Issue by faustoperez** [earthrise-media/food-system-digital-twin-website#32]
Hi @cameronkruse here's a quick content request list, following up on our meetings this week:

- To fine-tune the particles' behaviour:
   - Highest consumers/producers
   - Lowest consumers/producers
   - 3-4 examples of outliers/counties we want to make sure we get right
   - List with most linked counties examples
   - Adjacent counties examples

- Ideas or script for the intro screens

- About page content

Thank you!

**Comment by cameronkruse** [comment]
I responded in Slack with the max and min data. as for a few counties we want to get right:
- Miami-Dade County, FL has the most diverse production with 28 different crops produced
- Fresno, CA is a good one as it provides an abundance of fruits and vegetables to the west coast
- Los Angeles, CA, New York, NY, and Cook County, IL are all good urban counties to show demand

An adjacent county example could be any of the ones next to Fresno (Tulare, Merced, San Benito, and Inyo county).
